baseURL: "https://alirezasamar.com"
languageCode: "en-us"
title: Alireza Samar
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-4M9L51S50E

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Alireza Samar
  description: "Alireza Samar"
  keywords: [Blog, Publications, Machine Learning]
  author: Alireza Samar
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://raw.githubusercontent.com/alirezasamar/alirezasamar.github.io/master/assets/favicon/favicon.ico"
    favicon16x16: "https://raw.githubusercontent.com/alirezasamar/alirezasamar.github.io/master/assets/favicon/favicon-16x16.png"
    favicon32x32: "https://raw.githubusercontent.com/alirezasamar/alirezasamar.github.io/master/assets/favicon/favicon-32x32.png"
    apple_touch_icon: "https://raw.githubusercontent.com/alirezasamar/alirezasamar.github.io/master/assets/favicon/apple-touch-icon.png"
    safari_pinned_tab: "https://raw.githubusercontent.com/alirezasamar/alirezasamar.github.io/master/assets/favicon/favicon-16x16.png"

  label:
    text: "Alireza Samar"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: " "
    subtitle: |
      I am Alireza Samar, a computer scientist passionate about machine learning and data-intensive systems. <br>
      I lead a fabulous team of software and ML engineers at [Sievo](https://sievo.com). Previously, I built scalable and robust distributed systems at [Companio](https://companio.co), Segmentino and Appoint AI. <br>
      My current research focuses on the scalability of reinforcement learning, aiming to develop more efficient and robust RL systems. <br>
      The best way to reach me is via email ([alireza@[thiswebsite]]()). I am always open to interesting conversations and collaborations.

    imageUrl: "https://avatars.githubusercontent.com/u/3524061?v=4"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Alireza Samar
    buttons:
      - name: Blog
        url: blog
      - name: Tutorials
        url: tutorials
      - name: Publications
        url: publications

  permalinks:
    page:
      posts: /blog/:year/:month/:slug/
      # tutorials: /training/:slug/
    section:
      posts: /blog/
      # tutorials: /training/

  # home-info mode
  homeInfoParams:
    Title: "Welcome to my blog"
    Content: I'm Alireza and in this blog, my learning notes and musings are being documented. Other than writing a ML blog, I’m leading a fabulous` team of software/ML engineers at Sievo on the side.
    imageUrl: "https://raw.githubusercontent.com/alirezasamar/alirezasamar.github.io/master/assets/avatar/alirezasamar.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Alireza Samar

  socialIcons:
    - name: github
      url: "https://github.com/alirezasamar"
    - name: x
      url: "https://x.com/alirezasamar"
    - name: linkedin
      url: "https://www.linkedin.com/in/alirezasamar/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com/users/4105051"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=_t5fHe8AAAAJ&hl=en"
    # - name: kaggle
    #   url: "https://www.kaggle.com/alirezasamar"
    - name: goodreads
      url: "https://goodreads.com/alirezasamar"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  disqusShortname: alirezasamar

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true # Allows raw HTML in Markdown files
    extensions:
      typographer: true
      linkify: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
