baseURL: "https://alirsamar.com"
languageCode: "en-us"
title: Ali Samar
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-4M9L51S50E

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ali Samar
  description: "Ali Samar"
  keywords: [Blog, Publications, Machine Learning]
  author: Ali Samar
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://raw.githubusercontent.com/alirsamar/alirsamar.github.io/master/assets/favicon/favicon.ico"
    favicon16x16: "https://raw.githubusercontent.com/alirsamar/alirsamar.github.io/master/assets/favicon/favicon-16x16.png"
    favicon32x32: "https://raw.githubusercontent.com/alirsamar/alirsamar.github.io/master/assets/favicon/favicon-32x32.png"
    apple_touch_icon: "https://raw.githubusercontent.com/alirsamar/alirsamar.github.io/master/assets/favicon/apple-touch-icon.png"
    safari_pinned_tab: "https://raw.githubusercontent.com/alirsamar/alirsamar.github.io/master/assets/favicon/favicon-16x16.png"

  label:
    text: "Ali Samar"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "https://raw.githubusercontent.com/alirsamar/alirsamar.github.io/master/assets/avatar/alirsamar.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Ali Samar
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Welcome to my blog"
    Content: I'm Ali Samar and in this blog, my learning notes and musings are being documented. Other than writing a ML blog, I’m leading a fabulous` team of software/ML engineers at Sievo on the side.
    imageUrl: "https://raw.githubusercontent.com/alirsamar/alirsamar.github.io/master/assets/avatar/alirsamar.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Ali Samar

  socialIcons:
    - name: github
      url: "https://github.com/alirsamar"
    - name: twitter
      url: "https://twitter.com/alirsamar"
    - name: linkedin
      url: "https://www.linkedin.com/in/alirsamar/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com/users/4105051"
    # - name: googlescholar
    #   url: "https://scholar.google.com/citations?user=_t5fHe8AAAAJ&hl=en"
    # - name: kaggle
    #   url: "https://www.kaggle.com/alirsamar"
    - name: goodreads
      url: "https://goodreads.com/alirsamar"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  disqusShortname: alirsamar

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
